version: '3'
services:
  web:
    # Path to dockerfile
    build: .

    # Mapping of  host to container port
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.

    # Mapping of container port to host
    
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    # Mount volume
    volumes:
      #      - ./flask.sqlite:/myportfolio/flask.sqlite

      - .:/myportfolio
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data

volumes:
  mydatabase:
