version: '3'
services:
  web:
    # Path to dockerfile
    build: .

    # Mapping of  host to container port
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    # Mount volume
    volumes:
      - ./flask.sqlite:/myportfolio/flask.sqlite
