version: '3'
services:
  web:
    container_name: web_cturtles
    # Path to dockerfile
    build: .
    # Mapping of  host to container port
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.

    # Mapping of container port to host
    
    ports:
      - "5000:80"
    restart: always
    env_file:
      - .env
    # Mount volume
    volumes:
      #      - ./flask.sqlite:/myportfolio/flask.sqlite

      - .:/myportfolio
    depends_on:
      - db

  db:
    container_name: db_cturtles
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data
        
  nginx:
     container_name: nginx_cturtles
     image: jonasal/nginx-certbot:latest
     restart: unless-stopped
     env_file:
       - ./nginx-certbot.env
     ports:
       - 80:80
       - 443:443
     volumes:
       - /etc/letsencrypt/:/etc/letsencrypt
       - ./user_conf.d:/etc/nginx/user_conf.d
     depends_on:
       - web

volumes:
  mydatabase:
  nginx_secrets:
