name: Docker build

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    name: Run Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Docker Build
        run: |
          docker build .
